# Generated by Django 4.2 on 2023-04-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tg_employee',
            name='tg_employee_create',
            field=models.DateTimeField(help_text='Fecha de ingreso del empleado', null=True),
        ),
        migrations.AlterField(
            model_name='tg_employee',
            name='tg_employee_delete',
            field=models.DateTimeField(help_text='Fecha de retiro del empleado', null=True),
        ),
        migrations.AlterField(
            model_name='tg_employee',
            name='tg_employee_distric',
            field=models.TextField(help_text='Barrio del empleado', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tg_employee',
            name='tg_employee_surname',
            field=models.TextField(help_text='Segundo apellido del empleado', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tg_employee',
            name='tg_employee_update',
            field=models.DateTimeField(help_text='Fecha de actualización del empleado', null=True),
        ),
        migrations.AlterField(
            model_name='tg_employee',
            name='tg_employee_work_area',
            field=models.TextField(help_text='Area de trabajo del empleado', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tg_social_security',
            name='tg_social_security_create',
            field=models.DateTimeField(help_text='Fecha de ingreso de la empresa', null=True),
        ),
        migrations.AlterField(
            model_name='tg_social_security',
            name='tg_social_security_delete',
            field=models.DateTimeField(help_text='Fecha de retiro de la empresa', null=True),
        ),
        migrations.AlterField(
            model_name='tg_social_security',
            name='tg_social_security_update',
            field=models.DateTimeField(help_text='Fecha de actualización de la empresa', null=True),
        ),
    ]
