# Generated by Django 4.2 on 2023-04-06 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_alter_tg_employee_tg_employee_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tg_employee',
            name='tg_employee_update',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de actualización del empleado'),
        ),
        migrations.AlterField(
            model_name='tg_social_security',
            name='tg_social_security_update',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de actualización de la empresa'),
        ),
    ]
