# Generated by Django 4.2 on 2023-04-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_alter_tg_employee_tg_employee_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='tg_employee',
            name='tg_employee_id_type',
            field=models.TextField(default='cc', help_text='tipo de identificacion del empleado', max_length=2),
        ),
    ]
