# Generated by Django 4.2 on 2023-04-07 02:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0006_tg_employee_tg_employee_id_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tg_social_security',
            name='tg_social_security_email',
            field=models.EmailField(default='test@gmail.com', help_text='Correo de la empresa', max_length=254),
        ),
        migrations.AlterField(
            model_name='tg_social_security',
            name='tg_social_security_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 7, 2, 21, 29, 951837, tzinfo=datetime.timezone.utc), help_text='Fecha de actualización de la empresa'),
        ),
    ]
