# Generated by Django 4.2 on 2023-04-07 02:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0008_alter_tg_social_security_tg_social_security_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tg_social_security',
            name='tg_social_security_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 7, 2, 27, 20, 716397, tzinfo=datetime.timezone.utc), help_text='Fecha de actualización de la empresa'),
        ),
    ]
