# Generated by Django 4.2 on 2023-04-07 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0009_alter_tg_social_security_tg_social_security_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tg_social_security',
            name='tg_social_security_update',
            field=models.DateTimeField(help_text='Fecha de actualización de la empresa', null=True),
        ),
    ]
