# Generated by Django 4.2 on 2023-04-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0011_tg_city_tg_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tg_gender',
            name='tg_gender_name',
            field=models.TextField(help_text='Genero', max_length=1),
        ),
    ]
