# Generated by Django 4.2 on 2023-04-09 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0012_alter_tg_gender_tg_gender_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tg_employee',
            name='tg_employee_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.tg_city'),
        ),
        migrations.AlterField(
            model_name='tg_employee',
            name='tg_employee_gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.tg_gender'),
        ),
        migrations.AlterField(
            model_name='tg_social_security',
            name='tg_social_security_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.tg_city'),
        ),
    ]
